### ISSUE TITLE
500 error if I try to login with a wrong password

### ISSUE THREAD

**Issue by svetlichnaya** [space-ship-earth/pyspaceship#18]
or create a new account for that matter

**Comment by jeredw** [comment]
I pushed a new version of the site and this seems to be fixed now?

**Comment by igor47** [comment]
maybe can use updated logging in #47 to debug the issue conclusively?

**Comment by svetlichnaya** [comment]
works for me!

**Comment by igorkofman** [comment]
Seeing this again, was hoping to demo Micah. Lmk if anyone looks at this
and gets it working again
