### ISSUE TITLE
subresources should update after a push

### ISSUE THREAD

**Issue by jeredw** [space-ship-earth/pyspaceship#19]
Subresources (e.g. js, stylesheets) are cacheable and just named by filenames atm so pushing a new image doesn't update them. We could attach some kind of hash to these resources at build/deploy time so that browsers will get updated versions after a push?

**Comment by igor47** [comment]
@clizzin hey are you still working on this? ❤️

**Comment by clizzin** [comment]
Hi! I was not previously but am going to look at this right NAO.
