### ISSUE TITLE
Make it possible to see who is on a team and then Join without first logging in

### ISSUE THREAD

**Issue by igorkofman** [space-ship-earth/pyspaceship#70]
Approach 1
[ ] Make the team page not require sign-in to open, so that you can see who has already joined
[ ] Add a “Join” call to action on the team page (that lets you sign-in/sign-up)
Approach 2
[] The link to join a team should show you who is on the team already

**Comment by jeredw** [comment]
With approach 1 there is the concern of leaking emails by enumerating /roster/<id> so that would need to be addressed.

**Comment by igorkofman** [comment]
I don't think we need to show email addresses of users on the page anyway,
but yes!
