### ISSUE TITLE
Let the captain “Plan” a mission from the team page

### ISSUE THREAD

**Issue by igorkofman** [space-ship-earth/pyspaceship#71]
[ ] Let the captain “Plan” a mission from the team page by specifying a start date, this marks the mission as upcoming and shows it at the top of the team page

This probably requires a concept of a mission instance.  Perhaps our current missions table can be used to host mission instances (associated with a given team).

**Comment by jeredw** [comment]
+1 yes the current schema is that missions are prototypal objects, so a mission instance is just a mission (instances you do are cloned from a template, "frozen" and given a start date + team association).

**Comment by igorkofman** [comment]
- clean out missions and goals from db (deletes existing and inserts new goals)
- associate mission and team permanently (mission should have a team_id)

**Comment by clizzin** [comment]
Just to be clear, does this mean that some rows in the `missions` table represent templates, while other rows represent actual mission instances associated with a team?

I am personally partial to storing templates and actual instances of a thing in two different tables. I can roll with a single table if that's what others want though. Just asking to be clear on what people want.

**Comment by igorkofman** [comment]
No, I think we'd store "templates" in code for now, until we have more of
an idea of what we want here.

**Comment by clizzin** [comment]
Oh, I see, that is great too. Thanks!

**Comment by jeredw** [comment]
That makes sense to me too
