### ISSUE TITLE
Create initial post-mission survey

### ISSUE THREAD

**Issue by igor47** [space-ship-earth/pyspaceship#75]
what are we interested in after a mission ends: jeff's mockup:

![image](https://user-images.githubusercontent.com/200575/58298608-f626a080-7d90-11e9-9914-ca21b811ab72.png)

**Comment by svetlichnaya** [comment]
Here's a first pass: https://forms.gle/nGkNuYdBq2tRF8X37. Super open to feedback!

**Comment by igorkofman** [comment]
Nice!  It's currently framed as getting feedback on the mission, can we
frame it as "tell us how you did" instead?
We can have an optional section for feedback at the bottom?

Also, any chance we can cut this down and start with something that is max
3 questions?  My take would be:
- something about how they usually eat (I like you # of meals idea)
- something about how they ate this week (ditto - I think we can skip the
"are veggies all week if we ask number of meals)
- something open-ended

What do you think?

**Comment by svetlichnaya** [comment]
Sounds good. We can use your template from this most recent mission?
I can also make a shorter version of my full survey.

**Comment by davideg** [comment]
I like `@igorkofman`'s simplified survey :+1:

I also like @svetlichnaya's "More detailed feedback" section since it could give us really helpful feedback, but don't think it should be in users' faces immediately. How about making it opt-in with a link to an additional survey at the bottom of the main survey like: "Give us more detailed feedback [here]()"?

**Comment by igorkofman** [comment]
Sure! Or maybe we can edit down the more detailed feedback section to ~5
questions and include it but make it even more clearly Optional.

I don't love that main portion is 5 questions, I kinda wish it was three
but it seems worth  splitting out beef from non-beef.  Any suggested edits?
